#!/usr/bin/env zsh
# shellcheck shell=bash

dev () { #: prepare stuff and watch
	copy-static
	trap './task prod; exit 0' SIGINT
	npx vite
}
prod () { #: run through the whole pipeline
	npx vite build
	copy-static
}
install () { #: Install all dependencies
	composer install -no && npm ci
}
copy-static () { #: Install vendor assets
	echo "Copying static assets…"
	cp -rv assets/public/* public/assets/
}

favicon() { #: Generate favicon from SVG
	magick -density 300 -define icon:auto-resize=32,16 -background none assets/public/favicon.svg assets/public/favicon.ico
	magick assets/public/favicon.svg -resize 180x180 assets/public/apple-touch-icon.png
}

REMOTE_SERVER='--server--'
REMOTE_DIR='--website.sk--'
commit_live () { #: Spusti `commit_live` na servri a pullne zmeny na lokal
	ssh -t $REMOTE_SERVER "cd $REMOTE_DIR; ./task commit_content_locally"
	git pull
}
commit_content_locally () { #: Commitni a pushni zmeny na live webstranke (bezi na servri)
	git add content
	git commit -m "Zmeny na live webe - $(date '+%Y-%m-%d %H:%M') /skip-ci"
	git push
}

gst () { #: Zisti git status na live deployi 
	ssh -t $REMOTE_SERVER "cd $REMOTE_DIR; git status"
}

fonts () { #: subset fonts
	setopt extended_glob

	assets='assets/public'

	rm -r $assets/fonts 2>/dev/null
	mkdir -p $assets/fonts 2>/dev/null
	cp assets/fonts-raw/* ./$assets/fonts/

	wait

	for f in "$assets"/fonts/*; do
		glyphhanger --formats=woff2 --subset="$(dirname "$0")/$f" --css --LATIN --whitelist="ÁÄÉÍÓÔÚÝáäéíóôúýČĎŇŠŽčďňšžŤťŔŕĽľĹ" --string --json
	done


	wait
	rm ./$assets/fonts/^*subset.*
}

#
# BOILERPLATE
#
r='./task'
NAME='tpl-project-name'

h () { #: show help & commands
	echo "$NAME script runner"
	echo "Commands:"
	sed -nr 's/^(.*) \(\).* #: (.*)$/  \1\t\2/p' $r | expand -20
}

if [[ $# -gt 0 ]]; then
	command="$1"
	shift 1
	if type "$command" 2>/dev/null | grep -q 'function'; then
		$command "$@"
	else
		h
		echo "No command '$command'."
	fi;
else
	# about
	dev
fi
