#!/usr/bin/env zsh
# shellcheck shell=bash

REMOTE_SERVER='--server--'
REMOTE_DIR='--website.sk--'

dev () { #: prepare stuff and watch
	dev="public/assets/dev"
	
	npx hash-and-manifest empty
	clean-dev
	clean-dist

	COMMANDS=(
		#e26964 - browser-sync
		#62baf3 - tailwind
		#f7d147 - esbuild
		"npx browser-sync start --port 3000 --proxy 'http://tpl-project-local-domain.test/' --watch --files 'content' 'site' --open"
		"npx @tailwindcss/cli -i assets/main.css -o $dev/main.css --watch"
		"npx esbuild --bundle --watch --sourcemap assets/*.js --outdir=$dev"
	)
	NODE_ENV=development npx concurrently --prefix "█" -c "#e26964,#62baf3,#f7d147" "${COMMANDS[@]}"
}
prod () { #: run through the whole pipeline
	dist="public/assets/dist"
	export NODE_ENV=production
	clean-dev
	clean-dist
	vendor-assets

	# Site
	npx @tailwindcss/cli -i assets/main.css -o $dist/main.css --minify
	npx esbuild --bundle --target=es6 --minify assets/*.js --outdir=$dist

	npx hash-and-manifest
}
install () { #: Install all dependencies
	composer install -no && pnpm i
}

commit_live () { #: Spusti `commit_live` na servri a pullne zmeny na lokal
	ssh -t $REMOTE_SERVER "cd $REMOTE_DIR; ./task commit_content_locally"
	git pull
}

commit_content_locally () { #: Commitni a pushni zmeny na live webstranke (bezi na servri)
	git add content
	git commit -m "Zmeny na live webe - $(date '+%Y-%m-%d %H:%M') /skip-ci"
	git push
}

gst () { #: Zisti git status na live deployi 
	ssh -t $REMOTE_SERVER "cd $REMOTE_DIR; git status"
}

clean-dev() {
	rm -rf public/assets/dev
}
clean-dist() {
	rm -rf public/assets/dist
}
vendor-assets() {
	rsync -a assets/vendor public/assets
}

fonts () { #: subset fonts
	setopt extended_glob

	assets='public/assets'

	rm -r $assets/fonts 2>/dev/null
	mkdir -p $assets/fonts 2>/dev/null
	cp assets/fonts-raw/* ./$assets/fonts/

	wait

	for f in $assets/fonts/*; do
		glyphhanger --formats=woff2 --subset="$(dirname "$0")/$f" --css --LATIN --whitelist="ÁÄÉÍÓÔÚÝáäéíóôúýČĎŇŠŽčďňšžŤťŔŕĽľĹ" --string --json
	done


	wait
	rm ./$assets/fonts/^*subset.*
}

#
# BOILERPLATE
#
r='./task'
NAME='tpl-project-name'

h () { #: show help & commands
	echo "$NAME script runner"
	echo "Commands:"
	sed -nr 's/^(.*) \(\).* #: (.*)$/  \1\t\2/p' $r | expand -20
}

if [[ $# -gt 0 ]]; then
	command="$1"
	shift 1
	if type "$command" 2>/dev/null | grep -q 'function'; then
		$command "$@"
	else
		about
		echo "No command '$command'."
	fi;
else
	# about
	dev
fi
