#!/usr/bin/env zsh
# shellcheck shell=bash

REMOTE_SERVER='--server--'
REMOTE_DIR='--website.sk--'

dev () { #: prepare stuff and watch
	trap './task prod; exit 0' SIGINT
	npx vite
}
prod () { #: run through the whole pipeline
	npx vite build
}
install () { #: Install all dependencies
	composer install -no && pnpm i
}

commit_live () { #: Spusti `commit_live` na servri a pullne zmeny na lokal
	ssh -t $REMOTE_SERVER "cd $REMOTE_DIR; ./task commit_content_locally"
	git pull
}

commit_content_locally () { #: Commitni a pushni zmeny na live webstranke (bezi na servri)
	git add content
	git commit -m "Zmeny na live webe - $(date '+%Y-%m-%d %H:%M') /skip-ci"
	git push
}

gst () { #: Zisti git status na live deployi 
	ssh -t $REMOTE_SERVER "cd $REMOTE_DIR; git status"
}

clean-dev() {
	rm -rf public/assets/dev
}
clean-dist() {
	rm -rf public/assets/dist
}
vendor-assets() {
	rsync -a assets/vendor public/assets
}

fonts () { #: subset fonts
	setopt extended_glob

	assets='public/assets'

	rm -r $assets/fonts 2>/dev/null
	mkdir -p $assets/fonts 2>/dev/null
	cp assets/fonts-raw/* ./$assets/fonts/

	wait

	for f in $assets/fonts/*; do
		glyphhanger --formats=woff2 --subset="$(dirname "$0")/$f" --css --LATIN --whitelist="ÁÄÉÍÓÔÚÝáäéíóôúýČĎŇŠŽčďňšžŤťŔŕĽľĹ" --string --json
	done


	wait
	rm ./$assets/fonts/^*subset.*
}

#
# BOILERPLATE
#
r='./task'
NAME='tpl-project-name'

h () { #: show help & commands
	echo "$NAME script runner"
	echo "Commands:"
	sed -nr 's/^(.*) \(\).* #: (.*)$/  \1\t\2/p' $r | expand -20
}

if [[ $# -gt 0 ]]; then
	command="$1"
	shift 1
	if type "$command" 2>/dev/null | grep -q 'function'; then
		$command "$@"
	else
		about
		echo "No command '$command'."
	fi;
else
	# about
	dev
fi
